workflows:
  ios-native-quick-start:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment: 
      xcode: latest

    artifacts: 
      - build/ios/ipa/*.ipa
